agrc/forklift

src/forklift/plugin.py, tests/test_plugin.py, tox.ini
closes #3 
i renamed the tox env's to unit and lint to be more familiar.
I added --with-id to nose so --failed works
=> Define plugin baseclass

src/forklift/cli.py, tests/data/list_pallets/nested/pallets/nested.py, tests/test_cli.py
=> recursively search for pallets

src/forklift/__main__.py, src/forklift/cli.py, tests/test_cli.py
because I like crazy town.
closes #31
=> Log to both

src/forklift/models.py, tests/test_crate.py
=> turn wkid into spatialreference object

.gitignore, setup.py, src/forklift/__main__.py, src/forklift/cli.py, src/forklift/lift.py, src/forklift/models.py, tests/test_pallet.py
=> Console report

src/forklift/models.py, tests/test_pallet.py
=> Default reproject for Pallets

src/forklift/cli.py, src/forklift/report_template.html, tests/test_cli.py
=> Better cosnole

readme.md, src/forklift/models.py
Definitely more could be done but wanted to get at least something basic going...
=> basic doc updates

src/forklift/lift.py, tests/test_lift.py
=> Compact output fgdb's

samples/PalletSamples.py, src/forklift/cli.py, src/forklift/config.py, src/forklift/messaging.py, src/forklift/models.py, tests/test_cli.py, tests/test_config.py, tests/test_messaging.py
To test run lift against `PalletSamples.py` with `sendEmails: true` in your config.
Closes #43
=> Refactor email into messaging and add to pallet

tests/data/pallet_order.py, tests/test_cli.py
=> test for pallet order

src/forklift/core.py, src/forklift/models.py, tests/test_core.py, tests/test_pallet.py
Closes #55
Also includes the fix for #57
=> create destination_workspace on a crate if it doesn't already exist

src/forklift/cli.py
=> grab log from garage

.coveragerc, src/forklift/cli.py, src/forklift/lift.py, src/forklift/models.py, src/forklift/report_template.html, tests/data/report.json, tests/test_lift.py, tests/test_messaging.py
=> Pallet copy

src/forklift/core.py, src/forklift/lift.py
set the coordinate systems before we modify data or check for modifications to data so we can be assured that the correct transformation is being used.
=> Coordinate systems

src/forklift/__main__.py
=> add verbose flag to cli

src/forklift/__main__.py
forklift runs at 1:00AM so we should get a fresh log every day.
closes #100
=> change log handler to `midnight`

src/forklift/arcgis.py, src/forklift/cli.py, src/forklift/lift.py, src/forklift/report_template.html, tests/data/report.json, tests/test_arcgis.py, tests/test_cli.py, tests/test_lift.py
this should retry starting and stopping services 5 times with increasing delays.
It adds a line item to the forklift report for the result of the data copy.
I was not able to run all the tests due to my arcpy license manager issues so please let me know what's busted.
=> Stop and start services with retries

src/forklift/arcgis.py
Only log if there are problem children
=> tweak log for retrying services

src/forklift/cli.py, tests/data/duplicate_import.py, tests/test_cli.py
It messes with global members.
=> don't import the same module twice

src/forklift/cli.py
=> check for None as well as empty string

src/forklift/core.py, tests/test_core.py
I have a feeling that this will solve the OGM issue but haven't tested. I added a manually reset in that pallet just to be safe.
Either way this needed to be cleaned up.
=> better clean up of arcpy.env variables

src/forklift/cli.py, src/forklift/lift.py, src/forklift/report_template.html, tests/data/report.json, tests/test_cli.py, tests/test_lift.py
=> Git errors

src/forklift/cli.py, src/forklift/lift.py, src/forklift/report_template.html, tests/data/report.json
After changes:
Similar changes made to the command line report.
=> Better reporting when services fail to stop/start

src/forklift/cli.py, src/forklift/lift.py, src/forklift/models.py, tests/test_lift.py
=> add Pallet:post_copy_process

src/forklift/core.py
Change the temp suffix to something more recognizable.
Don’t project from within a search cursor because it does not honor the
geographic transformation environment variable.
=> Reproject data only once

setup.py, src/forklift/cli.py, src/forklift/core.py, src/forklift/models.py, tests/data/list_pallets/not_a_pllet.py, tests/test_core.py, tests/test_crate.py
=> Scott hashing

src/forklift/core.py, tests/test_core.py
Removed a few problems and added a test.
=> Delete hash if destination does not exist

readme.md
I should really do more PR's with stuff like this...
=> Added step to install git

src/forklift/models.py, tests/test_changes.py
=> return none for where clauses if adds OR deletes are above limit

.gitignore, src/forklift/core.py, src/forklift/models.py, tests/test_changes.py, tests/test_core.py
remove QUERY_LIMIT and chunked the adds and deletes
closes #159
This pull request removes QUERY_LIMIT short circuiting the where clause to None and chunks the adds and deletes by QUERY_LIMIT instead.
=> batching implemented for add and deletes

src/forklift/cli.py, src/forklift/core.py
the hash table is almost 2 gigs and changes a lot. we should compact it to be nice to our servers
=> compact hash and scratch gdbs

speedtest/SpeedTestPallet.py, src/forklift/cli.py, src/forklift/core.py, src/forklift/models.py, tests/test_changes.py
remove where clauses because 🐢 
table scan instead!
```
forklift\arcgis.py      65      3    95.38%   48, 96-98
forklift\cli.py        190     32    83.16%   138, 173-178, 185, 232-235, 289-323
forklift\core.py       229      8    96.51%   84-88, 156, 205, 351, 426
forklift\lift.py       128     26    79.69%   44-45, 131-152, 158, 176-177, 213-215, 228-229
forklift\models.py     168      6    96.43%   75, 257, 265, 317, 352-353
TOTAL                  869     75    91.37%
5 files skipped due to complete coverage.
-----------------------------------------------------------------------------
149 tests run in 98.691 seconds.
10 …
```
=> Table scan

src/forklift/__main__.py, src/forklift/messaging.py
https://files.slack.com/files-pri/T025LPV06-F44ND9X44/pasted_image_at_2017_02_13_07_26_am.png
should help with MemoryError
=> use gzip to make log files smaller

src/forklift/core.py
Closes #137
```
unit: commands succeeded
unit_installed: commands succeeded
lint: commands succeeded
congratulations :)
```
=> remove duplicate describe

src/forklift/models.py
=> add docs for arcgis_services pallet prop

setup.py
=> update and sort deps

MAINTAINERS, readme.md, setup.py, src/forklift/config.py, src/forklift/models.py, tests/test_cli.py
add `stagingDestination` to the config.
add `staging_rack` to Pallet with value from `stagingDestination` to allow for different staging destination locations without having to modify pallet/crate paths.
```
forklift\arcgis.py      65      3    95.38%   48, 96-98
forklift\cli.py        224     64    71.43%   138, 173-178, 185, 232-235, 283-300, 307-318, 328-377
forklift\core.py       244     11    95.49%   84-88, 155, 196, 204, 286, 295, 363, 438
forklift\lift.py       131     26    80.15%   45-46, 134-155, 161, 179-180, 216-218, 231-232
forklift\models.py     170      6    96.47%   79, 262, 270, 322, 357-358
TOTAL …
```
=> Staging folder

src/forklift/lift.py
Wraps `requires_processing` and `is_ready_to_ship` in try/catch statements so that they don't short circuit the entire process.
```
forklift\cli.py            224     63    71.88%   173-178, 185, 232-235, 283-300, 307-318, 328-377
forklift\core.py           244      9    96.31%   84-88, 155, 196, 204, 363, 438
forklift\lift.py           134     28    79.10%   45-46, 128-149, 155, 163-165, 180-181, 217-219, 232-233
forklift\models.py         170      4    97.65%   79, 322, 357-358
TOTAL                      928    107    88.47%
5 files skipped due to complete …
```
=> wrap requires_processing and is_ready_to_ship in try/catch

src/forklift/lift.py
This is to prevent the loss of the source static data when it is copied.
From https://docs.python.org/2/library/shutil.html docs, the copy method overwrites if necessary.
```
lint: commands succeeded
congratulations :)
forklift\cli.py            250     66    73.60%   111-112, 148, 183-188, 195, 242-245, 293-310, 317-328, 338-387
forklift\core.py           244      9    96.31%   84-88, 155, 196, 204, 363, 438
forklift\lift.py           155     28    81.94%   46-47, 164-185, 195-197, 209-211, 226, 234-236, 278-280
forklift\models.py         171      4    97.66%   85, 328, 363-364 …
```
=> move -> copy

src/forklift/core.py
This pull request swallows errors thrown by `arcpy.Delete_management()`. The gdb is successfully deleted despite the errors.
```
.............................................................................
.............................................................................
.
Name                    Stmts   Miss     Cover   Missing
--------------------------------------------------------
forklift\arcgis.py         65      3    95.38%   48, 96-98
forklift\cli.py           241     54    77.59%   111-112, 153, 188-193, 200, 247-250, 298-309, 313-322, 332-373
forklift\core.py          172      3    98.26%   119, 139, 322
forklift\lift.py          156     24    84.62%   155-175, 185-187, 199-201, 216, 224-226, 260, 275
forklift\messaging.py      33      1    96.97%   39 …
```
=> Swallow Pro Delete Errors

readme.md, run_forklift.bat
This will help people schedule forklift to run via Windows Scheduler.
=> add a sample batch file

src/forklift/arcgis.py
This pull requests adds a bit of documentation to the arcgis module
=> add a bit of doc

readme.md
=> update dev/test for non tox usage

src/forklift/arcgis.py, src/forklift/cli.py, src/forklift/config.py, tests/mocks.py, tests/test_arcgis.py, tests/test_cli.py, tests/test_core.py
This pull request parallelizes the code that clones/updates the git repositories.
Closes #204.
=> Parallelize git-update

src/forklift/cli.py, src/forklift/lift.py, src/forklift/models.py, tests/test_cli.py, tests/test_lift.py
This pull request implements the `prepare_packaging` method outlined in #190.
=> model.prepare_packaging

setup.py, src/forklift/__main__.py, src/forklift/arcgis.py
i believe this solves the python 2 issue. It does not stop the installation on 2 though. We might be able to do that in the setup.py somehow
Closes #218
=> do not allow python 2

src/forklift/core.py
Closes #223
Adds support for m & z values.
=> add support for m & z values in the destination

src/forklift/core.py
This is a more complete version of #224. I've confirmed that the m-values are actually copied to the output.
=> M & Z Values Support

src/forklift/models.py, tests/data/report_with_errors.json
This pull request adds a few more things to #226 including a fix to `Crate.set_result()` and updates to the email report template test data.
=> Fix Crate.set_result()

readme.md, src/forklift/__main__.py, src/forklift/cli.py, src/forklift/config.py, src/forklift/lift.py, tests/test_cli.py, tests/test_lift.py
This pull request builds upon the work that steve has been doing.
=> Scotts updates to grand canyon

src/forklift/engine.py, src/forklift/lift.py, tests/test_engine.py
Closes #242
All tests are passing...
=> chore: remove all_pallets return value from _build_pallets

src/forklift/config.py, tests/test_engine.py
Fixes #250
This pull request adds the missing configs.
=> fix: add missing creds to default server config

.gitignore, MANIFEST.in, readme.md, src/forklift/config.py, src/forklift/engine.py, src/forklift/lift.py, tests/test_engine.py, tests/test_lift.py
This pull request fixes the JSON stringifying exceptions bug and adjusts the manifest to include the new paths to the email template files.
=> Message fix

src/forklift/engine.py, tests/test_engine.py
feat: log packing slip contents
=> shipping enhancements

readme.md
=> readme readability update

.github/pull_request_template.md, readme.md, src/forklift/config.py, src/forklift/engine.py, tests/mocks.py, tests/test_engine.py
Forklift was hanging on git-update. This is in hopes of preventing this 
in the future.
=> Remove pool

src/forklift/models.py
=> fix: account for ERROR result in crate report

setup.py
=> fix: CVE-2018-18074

readme.md, src/forklift/engine.py
This pull requests allows for an object to be set in the repo's array
```json
"repositories": [{ 
"host": "https://gitlabs.com/",
"repo": "name/repo"
}]
```
=> allow for non github repos

samples/RunablePallet.py, src/forklift/models.py
This makes running pallets outside of forklift easier.
=> feat: add `init_standalone` method to Pallet class

samples/PalletSamples.py, samples/RunablePallet.py, src/forklift/config.py, src/forklift/messaging.py, tests/test_engine.py
This pull request adds a small paragraph to the end of all emails with the current forklift version.
```
----------- coverage: platform win32, python 3.6.8-final-0 -----------
Name                                                                                                  Stmts   Miss Branch BrPart     Cover   Missing
----------------------------------------------------------------------------------------------------------------------------------------------------
C:\Users\agrc-arcgis\AppData\Local\ESRI\conda\envs\forklift\Lib\site-packages\forklift\__main__.py       71
71     42      0     0.00%   3-189
C:\Users\agrc-arcgis\AppData\Local\ESRI\conda\envs\forklift\Lib\site-packages\forklift\arcgis.py        113
29     32      2    70.34%   26, 79-107, 137-138, 143, 146, 163, 181, …
```
=> Add forklift version to the bottom of all emails

src/forklift/engine.py
This fixes the shipping report.
=> fix: use correct prop name for pallet result and message

src/forklift/engine.py
This is to prevent us from thinking that the gift-wrap is shutting down the entire server...
=> fix: log actual services being shut down during gift-wrap ship

readme.md, src/forklift/core.py, src/forklift/engine.py, src/forklift/messaging.py, src/forklift/slack.py, tests/test_slack.py
lets you send the lift report to slack
need to add a slackWebhookUrl to the config. I'll send you ours if you want to try it.
refs #306
```
Name                                        Stmts   Miss Branch BrPart     Cover   Missing
------------------------------------------------------------------------------------------
C:\dev\forklift\src\forklift\arcgis.py        113     29     32      2    70.34%   26, 79-107, 137-138, 143, 146, 163, 181, 198-200, 222-224, 178->181, 197->198
C:\dev\forklift\src\forklift\config.py         50      1     20      2    95.71%   82, 81->82, 117->116
C:\dev\forklift\src\forklift\core.py          186      5     72      3    96.12%   122, 145-146, 345, 415, 121->122, 292->291, 414->415
C:\dev\forklift\src\forklift\engine.py        464    162    156     12 …
```
=> feat: ability to send lift report to slack

src/forklift/slack.py
this will fix the exception we got today
=> fix(slack): appended fields need to_text

samples/PalletSamples.py, src/forklift/__main__.py, src/forklift/core.py, src/forklift/engine.py, src/forklift/slack.py
This pull request improves error reporting on email and console reports. Specifically, it adds the machine name to global error emails and shows copy errors in ship emails and console reports.
I'm not sure if these need to be addressed in the slack reports.
```
```
```
```
=> Improve error reporting

src/forklift/change_detection.py
I missed that this argument defaulted to 'TEST'...
=> fix: explicitly specify no test for change detection append

readme.md
Pro upgrades are a LOT easier now...
=> docs: update to use fresh conda env with arcpy install

src/forklift/engine.py, src/forklift/messaging.py
fixes 
> AttributeError: 'str' object has no attribute 'name'
=> fix: make path a path

src/forklift/core.py
Getting a data update without metadata is better than no update at all.
=> fix: metadata fails for some agol services

readme.md
This pull requests ...
```
```
```
```
=> docs: define python version when creating environment

src/forklift/lift.py
This pull requests replaces `shutil.copytree` with `robocopy`
```
```
```
```
=> Use robocopy instead of shutil

.github/pull_request_template.md, setup.py
=> deps: bump deps suggested by dependabot

src/forklift/__main__.py
This was causing issues [in auditor](https://github.com/agrc/auditor/pull/93) so I'm preemptively fixing it in forklift even though it doesn't seem to be having the same issue.
=> fix: fix handler import

src/forklift/engine.py, src/forklift/templates/ship.html, tests/test_change_detection.py
All tests are passing on my machine.
=> Add git update to ship process
