agrc/forklift

- src/forklift/core.py
- tests/test_core.py
I want to have access to this from within custom `Pallet.validate_crate` functions so that I can check the schemas and then do custom validation.
> core._check_schema -> core.check_schema

- src/forklift/cli.py
- tests/data/alphabetize/pallet.py
- tests/test_cli.py
The use case is the DEQ pallet which loads a bunch of temp data with
one pallet then acts on that data with other pallets.
> execute pallets in alphabetical order

- src/forklift/cli.py
- src/forklift/messaging.py
- tests/test_messaging.py
- tox.ini
Attach log file instead of inlining it. 
Do not create SMTP instance if it is not used.
Create local .eml files for testing.
> Log sent as email attachment

- src/forklift/lift.py
- src/forklift/models.py
This cleans up the logs and prevents the methods from being called
before `build`. This can cause a problem if the method is dependent on
something
> remove method calls from Pallet.__repr__

- src/forklift/lift.py
- tests/test_lift.py
I struggled to decide if this is a pallet concern but I decided it should end up in forklift since it breaks downstream pallets. I wonder if we need to be more paranoid and reset the workspace after all of the
places pallets could use it?
closes https://github.com/agrc/warehouse/issues/31
> reset env between ship

- .github/pull_request_template.md
- src/forklift/cli.py
- src/forklift/core.py
- src/forklift/models.py
this mornings failure may have been caused by the staging or hourly
scripts using the scratch gdb at the same time as the prod script. Let's
remove the splinter that is the scratch gdb and keep all of our temp
assets in the garage.
```
forklift\cli.py            185     27    85.41%   136, 171-176, 183, 230-233, 287-316
forklift\core.py           224     14    93.75%   131, 167-168, 177, 185, 242-254, 282, 325, 400
forklift\lift.py           127     26    79.53%   44-45, 131-152, 158, 176-177, 213-215, 228-229
forklift\models.py         188      6    96.81%   77, 260, 268, 315, 350-351 …
```
> use our own scratch gdb

- src/forklift/cli.py
- src/forklift/core.py
- tests/test_core.py
The allows the deq hourly to use core without using the same logger as the rest of forklift. The deq hourly logs now have their own file name (`deqhourly.log`).
```
forklift\cli.py            189     32    83.07%   136, 171-176, 183, 230-233, 287-321
forklift\core.py           217      8    96.31%   137, 173-174, 183, 191, 257, 331, 406
forklift\lift.py           127     26    79.53%   44-45, 131-152, 158, 176-177, 213-215, 228-229
forklift\models.py         190      4    97.89%   77, 319, 354-355
TOTAL                      877     73    91.68%
5 files …
```
> Don't define logger in core

- src/forklift/lift.py
- tests/test_lift.py
This prevents paths such as `C:\\Scheduled\\staging\\political_utm.gdb` and `C:\\\\Scheduled\\staging\\political_utm.gdb` from being treated a separate workspaces. This was preventing the services from the PoliticalDistricts pallet from being shut down when the data from the Hava pallet was updated even thought they were pointed at the same `copy_data` geodatabase.
```
forklift\cli.py            189     32    83.07%   136, 171-176, 183, 230-233, 287-321
forklift\core.py           227      9    96.04%   75, 146, 187-188, 197, 205, 271, 345, 420
forklift\lift.py           128     26    79.69%   44-45, 131-152, 158, …
```
> Normalize copy_data paths

- src/forklift/core.py
- src/forklift/lift.py
Let's try reseting the [workspace cache](http://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/clear-workspace-cache.htm) after each pallet. It's all over http://support.esri.com/technical-article/000011679
refs https://github.com/agrc/warehouse/issues/38
```
forklift\arcgis.py      65      3    95.38%   48, 96-98
forklift\cli.py        224     64    71.43%   138, 173-178, 185, 232-235, 283-300, 307-318, 328-377
forklift\core.py       233     10    95.71%   84-88, 155, 199, 281, 290, 358, 433
forklift\lift.py       131     26    80.15%   45-46, 134-155, 161, 179-180, 216-218, 231-232
forklift\models.py     168      6    96.43%   75, 257, 265, 317, 352-353 …
```
> try resetting workspace cache for compresses

- src/forklift/__main__.py
- src/forklift/cli.py
- src/forklift/lift.py
- src/forklift/models.py
- tests/test_cli.py
- tests/test_lift.py
Add `static_data String[]` property to the `Pallet` class.
Add `update_static <file-path>` command for updating the static data for a specific pallet.
Add check for static data in `lift` command.
Unrelated: Fix global error handler so that it actually emails us.
Ref: #131
```
forklift\cli.py            242     78    67.77%   109-110, 181-186, 193, 240-243, 291-308, 315-326, 336-385, 395-415
forklift\core.py           244      9    96.31%   84-88, 155, 196, 204, 363, 438
forklift\lift.py           152     40    73.68%   46-47, 133-153, 169-190, 200-202, 214-216, 231, 276-278
forklift\models.py         171      4 …
```
> add static_data property to pallets and associated cli option

- src/forklift/__main__.py
- src/forklift/cli.py
- tests/test_cli.py
This pull requests adds a new cli command: `scorched-earth`. It deletes the scratch and hashes GDBs and everything in the staging folder.
```
```
```
```
> implement scorched-earth command

- src/forklift/cli.py
- src/forklift/lift.py
Fixes #186
This pull request makes sure that `pallet.build(config)` gets called for all pallets in the config rather than just the one getting lifted.
This will make testing individual pallets easier.
```
Name                    Stmts   Miss     Cover   Missing
--------------------------------------------------------
forklift\arcgis.py         65      3    95.38%   48, 96-98
forklift\cli.py           242     54    77.69%   111-112, 148-149, 156, 191-196, 203, 301-312, 316-325, 335-376
forklift\core.py          174      3    98.28%   119, 139, 322
forklift\lift.py          156     24    84.62%   155-175, 185-187, 199-201, 216, 224-226, 260, 275
forklift\messaging.py      33      1    96.97%   39
forklift\models.py        172      4    97.67%   86, 319, 362-363 …
```
> Call build on all pallets when a single one is lifted

- src/forklift/lift.py
This pull request adds an ignore to the copy to `copy_data` that ignores `*.lock` files. This is helpful for pallets that use `MakeFeatureLayer` and leave schema locks on files.
```
Name                    Stmts   Miss     Cover   Missing
--------------------------------------------------------
forklift\arcgis.py         65      3    95.38%   48, 96-98
forklift\cli.py           242     54    77.69%   111-112, 148-149, 156, 191-196, 203, 301-312, 316-325, 335-376
forklift\core.py          174      3    98.28%   119, 139, 322
forklift\lift.py          156     24    84.62%   155-175, 185-187, 199-201, 216, 224-226, 260, 275
forklift\messaging.py      33      1    96.97%   39
forklift\models.py        172      4    97.67%   86, 319, 362-363 …
```
> Ignore *.lock files when copying to `copy_data`

- src/forklift/cli.py
- src/forklift/core.py
Pro is throwing Oracle lock errors when we try to delete this database. Since it's deleted at the beginning of the process, we can just drop this method.
> remove deletion of scratch gdb from the end of the process

- .flake8
- src/forklift/arcgis.py
- tests/test_cli.py
- tests/test_core.py
- tox.ini
This allows LightSwitch code to be reused on more than the server configured in the environmental variables. 
```
forklift\arcgis.py      79     12    84.81%   31-41, 71, 119-121
forklift\cli.py        241     54    77.59%   111-112, 153, 188-193, 200, 247-250, 298-309, 313-322, 332-373
forklift\core.py       172      3    98.26%   119, 139, 322
forklift\lift.py       156     24    84.62%   155-175, 185-187, 199-201, 216, 224-226, 260, 275
forklift\models.py     172      8    95.35%   86, 268-271, 319, 362-363
TOTAL                  911    101    88.91%
5 files skipped due to complete coverage. …
```
> allow updating of LightSwitch credentials

- src/forklift/cli.py
- src/forklift/lift.py
- src/forklift/models.py
- src/forklift/report_template.html
- tests/ReportTests.html
- tests/data/report_success.json
- tests/data/report_with_errors.json
- tests/test_cli.py
- tests/test_crate.py
- tests/test_lift.py
The pull request enhances the reports (both email/HTML and command line) to be easier to read. It also adds:
- the ability for crates to report warnings paving the way for #128 & #185.
- fixes the annoying thin red line showing up at the top of successful reports (see b00e02e):
Example Reports:
> Report Improvements Including Warnings

- src/forklift/core.py
- src/forklift/models.py
the tests hang for me. I pip installed multiprocess but it still hug on 
```
(forklift) λ nosetests --with-id --rednose --cov-config .coveragerc --with-coverage --cover-package forklift --cov-report term-missing --cover-erase
........................................Traceback (most recent call last):
File "<string>", line 1, in <module>
ImportError: No module named 'multiprocess'
```
> Warnings are not errors

- src/forklift/arcgis.py
This pull requests adds a timeout to requests
```
forklift\arcgis.py      94     16    82.98%   34-44, 71, 125-128, 137-139
forklift\cli.py        264     51    80.68%   88, 125-126, 206-211, 244, 349-360, 364-373, 383-424
forklift\core.py       182      2    98.90%   119, 324
forklift\lift.py       166     24    85.54%   179-199, 209-211, 223-225, 240, 248-250, 284, 299
forklift\models.py     191      8    95.81%   99, 294-297, 353, 397-398
TOTAL                  997    101    89.87%
5 files skipped due to complete coverage.
-----------------------------------------------------------------------------
161 tests run in 353.896 …
```
> Add 30 second timeout to requests

- src/forklift/arcgis.py
This reverts commit 83fd9c664e3e90eae714b146fdcaa62e13b8df5c.
I think that the way that we are doing it is correct. Ref: https://docs.python.org/3/tutorial/modules.html#intra-package-references
> Revert "allow for easier testing"

- src/forklift/arcgis.py
This pull request increases the timeout for the start and stop service requests to ArcGIS Server. We had a bunch of services returned from forklift as unable to start this morning. However, when I went to check on them, all but one were started. Hopefully, this will prevent forklift crying wolf in the future.
I didn't feel like this change was worth running any.
> increase arcgis server request timeout from 30 to 60 seconds

- src/forklift/arcgis.py
This pull request increases the timeout for the start/stop of ArcGIS Server services. The last few days we've been getting errors in forklift that report services not starting successfully. However, when I go to check them they are started.
n/a
n/a
> [WIP] increase timeout for starting/stopping service request

- src/forklift/__main__.py
- src/forklift/messaging.py
- tests/test_messaging.py
This pull request adds a new optional parameter (`--skip-emails`) to the `lift` command for temporarily switching off the sending of emails. This will prevent the situation where absent-minded people, such as myself, forget to update the switch in the config file.
> add -skip-emails optional parameter

- src/forklift/models.py
We need a way to manually set an error on a crate from within a pallet. For example:
https://github.com/agrc/warehouse/blob/8e195f69dc4097efb12fc5326b0e3d1ebc95f002/sgid/AGOLPallet.py#L84
I didn't think that `UNHANDLED_EXCEPTION` was a good fit.
> Add `ERROR` result type to crate

- setup.py
The two newest versions that are installed with the 0.* specs are not compatible.
> pin multiprocess and dill dependencies

- src/forklift/templates/lift.html
- src/forklift/templates/ship.html
closes #257
switched `b` to `strong`
moved the strong text to the pallet
> feat: improve email report readability

- src/forklift/engine.py
- src/forklift/models.py
- tests/test_engine.py
This pull request fixes the email report for pallets that use `is_ready_to_ship` to restrict which days that pallet runs. Any ideas on why we used `is_ready_to_ship` to get the success value for the lift report in the first place?
Before PR:
After PR:
> report should be based on pallet.success not is_ready_to_ship

- src/forklift/arcgis.py
This pull requests broadens the error catching for http requests to server. there is no reason to be specific when returning the same item from each case.
I don't know why arcgis server was refusing connections. but that should not kill the update process.
> Catch all errors

- src/forklift/lift.py
This allows for pallets that generate data rather define crates to have 
their data copied to the drop off location by overwriting 
requires_processing (which they are likely already doing anyway).
This was specifically done to help with the new [SureSites pallet](https://github.com/agrc/locate/pull/177).
> fix: allow pallets that don't have any crates to copy data to dropoff

- src/forklift/core.py
If this is left as an Exception object, it causes an error when trying to build the console report.
> fix: return unhandled crate exceptions as strings

- src/forklift/core.py
- src/forklift/models.py
Closes #255
```
----------- coverage: platform win32, python 3.6.8-final-0 -----------
Name                                                                                                  Stmts   Miss Branch BrPart     Cover
Missing
----------------------------------------------------------------------------------------------------------------------------------------------------
C:\Users\agrc-arcgis\AppData\Local\ESRI\conda\envs\forklift\Lib\site-packages\forklift\__main__.py       71     71     42      0     0.00%
3-189
C:\Users\agrc-arcgis\AppData\Local\ESRI\conda\envs\forklift\Lib\site-packages\forklift\arcgis.py        113     29     32      2    70.34%
26, 79-107, 137-138, 143, 146, 163, 181, 198-200, 222-224, 178->181, 197->198 …
```
> fix: arcpy.Describe -> arcpy.da.Describe

- samples/RunablePallet.py
- src/forklift/__main__.py
- src/forklift/engine.py
- src/forklift/messaging.py
- tests/test_messaging.py
```
Name                                                                                                  Stmts   Miss Branch BrPart     Cover
Missing
----------------------------------------------------------------------------------------------------------------------------------------------------
C:\Users\agrc-arcgis\AppData\Local\ESRI\conda\envs\forklift\Lib\site-packages\forklift\__main__.py       71     71     42      0     0.00%
3-189
C:\Users\agrc-arcgis\AppData\Local\ESRI\conda\envs\forklift\Lib\site-packages\forklift\arcgis.py        113     29     32      2    70.34%
26, 79-107, 137-138, 143, 146, 163, 181, 198-200, 222-224, 178->181, 197->198
C:\Users\agrc-arcgis\AppData\Local\ESRI\conda\envs\forklift\Lib\site-packages\forklift\config.py         50      1     20      2 …
```
> Add packing slip to lift report email

- samples/TypicalPallet.py
- src/forklift/engine.py
- src/forklift/models.py
This pull requests fixes the report to show how long it took to ship a pallet. Prior the report was using the lift time.
```
----------- coverage: platform win32, python 3.6.5-final-0 -----------
Name                                        Stmts   Miss Branch BrPart     Cover   Missing
------------------------------------------------------------------------------------------
C:\dev\forklift\src\forklift\arcgis.py        113     29     32      2    70.34%   26, 79-107, 137-138, 143, 146, 163, 181, 198-200, 222-224, 178->181, 197->198
C:\dev\forklift\src\forklift\config.py         50      1     20      2    95.71%   82, 81->82, 117->116
C:\dev\forklift\src\forklift\core.py          186      5     72      3    96.12%   122, 145-146, 345, 415, 121->122, 292->291, 414->415 …
```
> Ship timer for report

- src/forklift/engine.py
- src/forklift/models.py
- tests/test_engine.py
This pull request fixes a bug that was overwriting the manually set pallet result with the associated packing slip pallet result causing false positives.
```
====================================== test session starts ======================================
platform win32 -- Python 3.6.8, pytest-4.6.5, py-1.8.0, pluggy-0.13.0
rootdir: C:\Projects\forklift, inifile: pytest.ini
plugins: cov-2.7.1, instafail-0.4.1, isort-0.3.1, pylint-0.14.1
collected 244 items                                                                              
-----------------------------------------------------------------
Linting files
.
-----------------------------------------------------------------
setup.py ss                                                                             [  2/244] …
```
> Ship pallet report status

- src/forklift/__main__.py
- src/forklift/engine.py
- src/forklift/lift.py
This pull request adds a new optional argument to the `gift-wrap` command. It also tweaks it's behavior a bit in an attempt to make it a more smooth experience when using it to gift wrap data directly into receiving.
```
============================================= test session starts =============================================
platform win32 -- Python 3.6.8, pytest-4.6.5, py-1.8.0, pluggy-0.13.0
rootdir: W:\forklift, inifile: pytest.ini
plugins: cov-2.7.1, instafail-0.4.1, isort-0.3.1, pylint-0.14.1
collected 244 items                                                                                            
-----------------------------------------------------------------
Linting files
........................................ …
```
> Add pallet argument to `gift-wrap`

- src/forklift/engine.py
I don't believe that this is needed now that gift-wrap uses `lift.copy_with_overwrite`. This will save the user from having to manually copy the data after running the command.
> fix: remove the creation of "gift-wrapped" subfolder

- src/forklift/models.py
- tests/test_pallet.py
Some pallets (e.g. AGOLPallet) want processing to happen despite there being errors in some datasets. This PR adds an optional argument to `Pallet.requires_processing` that allows you to ignore the errors.
```
=============================== test session starts ================================
platform win32 -- Python 3.6.9, pytest-4.6.5, py-1.8.0, pluggy-0.12.0
rootdir: W:\forklift, inifile: pytest.ini
plugins: cov-2.7.1, instafail-0.4.1.post0, isort-0.3.1, pylint-0.14.1
collected 245 items                                                                 
-----------------------------------------------------------------
Linting files
.
-----------------------------------------------------------------
setup.py ss                                                                [  2/245] …
```
> feat: add ability to ignore changes in requires processing

- src/forklift/models.py
- tests/test_pallet.py
This pull request handles the situation where there are mis-matching crates between a built pallet (during ship) and the packing slip.
```
(forklift) λ pytest -k test_pallet.py
========================== test session starts ===========================
platform win32 -- Python 3.6.9, pytest-4.6.5, py-1.8.0, pluggy-0.12.0
rootdir: W:\forklift, inifile: pytest.ini
plugins: cov-2.7.1, instafail-0.4.1.post0, isort-0.3.1, pylint-0.14.1
collected 251 items / 218 deselected / 33 selected                        
-----------------------------------------------------------------
Linting files
.........
-----------------------------------------------------------------
tests\test_pallet.py .................................             [33/33]
----------- coverage: platform win32, python 3.6.9-final-0 …
```
> fix: handle mis-matching crates between pallet and packing list

- src/forklift/change_detection.py
This is causing issues with data that has additional fields added during processing. I don't believe that we need it since [we check the schemas of source and destination before this code runs](https://github.com/agrc/forklift/blob/d442f7b7d866527ab886fbd2db82e1afa7af7072/src/forklift/core.py#L90).
> fix: make append more flexible with differing schemas

- src/forklift/models.py
- tests/test_crate.py
This allows for database sources that have less than three parts when split by a ".".
Co-authored-by: steveoh <sgourley@utah.gov>
```
=========================================================================================== test session starts ============================================================================================
platform win32 -- Python 3.6.9, pytest-4.6.5, py-1.8.0, pluggy-0.12.0
rootdir: W:\forklift, inifile: pytest.ini, testpaths: tests
plugins: cov-2.7.1, instafail-0.4.1.post0, isort-0.3.1, pylint-0.14.1
collected 209 items …
```
> fix: handle more database sources name formats

- src/forklift/engine.py
Prevent the entire forklift process from crashing if there's an issue posting the report to slack.
> fix: handle errors posting report to slack

- readme.md
I was able to generate this on the command line using `standard-version` and then copy-paste into the changelog with a little clean up.
> chore: v9.3.0 changelog

- src/forklift/core.py
- tests/test_core.py
This pull request adds global id fields to the change detection hash. Now that we are concerned with them being preserved in the crate destination, we should include them. I'm thinking that the same thing should be done [in cambiador](https://github.com/agrc/cambiador/blob/622bd07b9d532d50c3881e7dfddb128cfef5f631/Program.cs#L114). @steveoh, any concerns with making this same change in cambiador?
```
========================================================================================= test session starts ==================================pylint-0.18.0=======================================================                                                                                                                                                
platform win32 -- Python 3.7.10, …
```
> fix: include global id fields in hash

- readme.md
- setup.py
- src/forklift/config.py
- src/forklift/messaging.py
- tests/test_engine.py
This pull requests uses send grid emailing if there is an api key in the config. I have an api key created already that we can use.
I believe this should work but I don't have forklift installed currently. Can we go through it together? I did test the mail sending code outside of the forklift project and that worked wonderfully.
> add sendgrid mail client

- run_forklift_ship_lift.bat
I believe that this will prevent the lift process from overwriting the staged data that may or may not have been copied to production if there was a global error during ship.
> fix: only run lift if ship process is successful

- src/forklift/messaging.py
This was popping a syntax warning.
> fix: don't use `is not` with literals

- pytest.ini
- src/forklift/config.py
- src/forklift/engine.py
- tests/test_change_detection.py
- tests/test_config.py
- tests/test_core.py
- tests/test_crate.py
- tests/test_lift.py
I believe that before this change, you had to have an options prop even if you had no servers.
```
============================================================== test session starts ===============================================================
platform win32 -- Python 3.9.11, pytest-6.2.4, py-1.11.0, pluggy-0.13.1
rootdir: C:\projects\forklift, configfile: pytest.ini, testpaths: tests
plugins: cov-3.0.0, instafail-0.4.2, isort-2.0.0, pylint-0.19.0
collected 218 items                                                                                                                               
--------------------------------------------------------------------------------
Linting files
....................................
------------------------------------------------------------------- …
```
> fix: handle null value for servers

- src/forklift/messaging.py
> fix: fix attachement name for smtp emails

- src/forklift/core.py
This is to handle a new field type that showed up after DEQ made a schema change. Here's the error message that I hope to solve with it:
```
DEBUG   01-09 01:46:45       core:   81 c:\forklift\data\hashed\deqquerylayers_temp.gdb\TRI does not exist. creating
WARNING 01-09 01:46:47       core:  284 creating new table: c:\forklift\data\hashed\deqquerylayers_temp.gdb\TRI
ERROR   01-09 01:46:52       core:  164 unhandled exception: 'BigInteger' for crate source: [c:\forklift\warehouse\deq-enviro\scripts\nightly\settings\..\databases\cercla.sde\cercla.Arcserver.PTN_TRI] source_workspace: [c:\forklift\warehouse\deq-enviro\scripts\nightly\settings\..\databases\cercla.sde] destination: [c:\forklift\data\hashed\deqquerylayers_temp.gdb\TRI]
Traceback (most recent call last):
File …
```
> fix: add missing source field type

- setup.py
v21 was conflicting with the cryptography package which I think is a dependency of some of the pallets. Bumping to 23 fixes the issue. 
Ref: https://stackoverflow.com/questions/74981558/error-updating-python3-pip-attributeerror-module-lib-has-no-attribute-openss
> fix: bump pyopenssl to remove conflicts
